fail_fast: true
repos:
  - repo: meta
    hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: trailing-whitespace
      exclude: \.md$
    - id: check-toml
    - id: mixed-line-ending
  - repo: local
    hooks:
      - id: sort-pyproject
        name: sort pyproject
        files: ^pyproject\.toml$
        language: system
        entry: uv run -- toml-sort -i --sort-table-keys --sort-inline-tables
      - id: ruff-format
        name: ruff format
        types_or: [python, pyi, jupyter, toml]
        language: system
        entry: uv run -- ruff format --
        require_serial: true
      - id: ruff-lint
        name: ruff lint
        types_or: [python, pyi, jupyter, toml]
        language: system
        entry: uv run -- ruff check --fix --
        require_serial: true
      - id: pyright
        name: pyright
        types_or: [python]
        language: system
        entry: uv run -- pyright
        require_serial: true
