name: Build docs

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv run echo done

      - name: Build docs
        run: |
          uv run mkdocs build

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: site  # where `mkdocs build` puts the built site
